# Generated by Django 3.0.3 on 2020-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceImg',
            field=models.ImageField(upload_to=''),
        ),
    ]
