# Generated by Django 3.0.3 on 2020-08-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200811_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Post', models.CharField(max_length=120)),
                ('description', models.ImageField(upload_to='service_pics')),
            ],
        ),
    ]
